apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: blue
  namespace: default
spec:
  interval: 1m
  secretRef:
    name: git-auth
  url: https://github.com/gitops-remote-dev/blue
  ref:
    branch: master
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: blue
  namespace: default
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: blue
  path: ./deploy/develop
  prune: true
