apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: telepresence
spec:
  releaseName: telepresence
  chart:
    spec:
      chart: telepresence
      sourceRef:
        kind: HelmRepository
        name: ambassador
        namespace: flux-system
      version: "2.4.9"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: telepresence-values
